// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ActivityWatchVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "ActivityWatchVS.ea6d1160-0387-4c74-9caf-1f9fcabf5ea5";
        public const string Name = "ActivityWatchVS";
        public const string Description = @"Track your work with this plugin and activitywatch.net. Ever wanted to know where you spend your time?
The Plugin is a Watcher for Visual Studio. It enables tracking of all, you do in your solution. We send this data to an Activity Watch installation on your machine, all tracked data belongs to you.

Activity Watch tracks windows titles, we extend this functionality from inside Visual Studio and track your file edits.";
        public const string Language = "en-US";
        public const string Version = "1.9.0";
        public const string Author = "Florian Lagg";
        public const string Tags = "Activity Watch, quantified self, lifelog, coding, tracking";
    }
}
